// <auto-generated />
using System;
using Buckl.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Buckl.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BucklDbContext))]
    [Migration("20260922235242_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Buckl.Infrastructure.Persistence.Records.GarmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("PhotoKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("photo_key");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("PurchaseAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("purchase_amount");

                    b.Property<string>("PurchaseCurrency")
                        .HasColumnType("character(3)")
                        .HasColumnName("purchase_currency");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("size");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_garments");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("garments_product_idx")
                        .HasFilter("product_id is not null");

                    b.HasIndex("UserId", "Category")
                        .HasDatabaseName("garments_owner_category_idx");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("garments_owner_status_idx");

                    b.ToTable("garments", null, t =>
                        {
                            t.HasCheckConstraint("garments_archived_at_matches_status", "(status = 'archived' and archived_at is not null) or (status = 'active' and archived_at is null)");

                            t.HasCheckConstraint("garments_category_values", "category in ('top', 'bottom', 'dress', 'outerwear', 'footwear', 'accessory')");

                            t.HasCheckConstraint("garments_color_values", "color in ('black', 'white', 'grey', 'navy', 'blue', 'red', 'green', 'yellow', 'brown', 'beige', 'pink', 'purple', 'orange', 'multicolor')");

                            t.HasCheckConstraint("garments_photo_key_under_owner", "photo_key is null or photo_key like 'users/' || user_id::text || '/_%'");

                            t.HasCheckConstraint("garments_purchase_all_or_none", "(purchase_amount is null and purchase_currency is null and purchase_date is null) or (purchase_amount is not null and purchase_currency is not null and purchase_date is not null)");

                            t.HasCheckConstraint("garments_purchase_amount_not_negative", "purchase_amount is null or purchase_amount >= 0");

                            t.HasCheckConstraint("garments_purchase_currency_format", "purchase_currency is null or purchase_currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("garments_size_not_blank", "size is null or length(btrim(size)) > 0");

                            t.HasCheckConstraint("garments_source_values", "source in ('manual', 'url', 'email')");

                            t.HasCheckConstraint("garments_status_values", "status in ('active', 'archived')");

                            t.HasCheckConstraint("garments_updated_not_before_created", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("Buckl.Infrastructure.Persistence.Records.ProductRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ReferenceImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("reference_image_url");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("SourceUrl")
                        .IsUnique()
                        .HasDatabaseName("products_source_url_key")
                        .HasFilter("source_url is not null");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("products_brand_not_blank", "brand is null or length(btrim(brand)) > 0");

                            t.HasCheckConstraint("products_image_url_https", "reference_image_url is null or reference_image_url like 'https://%'");

                            t.HasCheckConstraint("products_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("products_source_url_scheme", "source_url is null or source_url like 'http://%' or source_url like 'https://%'");

                            t.HasCheckConstraint("products_source_values", "source in ('manual', 'url', 'email')");
                        });
                });

            modelBuilder.Entity("Buckl.Infrastructure.Persistence.Records.UserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth0Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth0_subject");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Auth0Subject")
                        .IsUnique()
                        .HasDatabaseName("users_auth0_subject_key");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Buckl.Infrastructure.Persistence.Records.GarmentRecord", b =>
                {
                    b.HasOne("Buckl.Infrastructure.Persistence.Records.ProductRecord", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_garments_products_product_id");

                    b.HasOne("Buckl.Infrastructure.Persistence.Records.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_garments_users_user_id");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
